server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.116:8848
    sentinel:
      transport:
        # \u914D\u7F6Esentinel dashborard \u5730\u5740
        dashboard: localhost:8080
        # \u9ED8\u8BA48719 \u7AEF\u53E3\uFF0C\u5047\u5982\u88AB\u5360\u7528\u4F1A\u81EA\u52A8\u4ECE8719 \u5F00\u59CB\u4F9D\u6B21+1 \u626B\u63CF\uFF0C\u76F4\u81F3\u627E\u5230\u672A\u88AB\u5360\u7528\u7684\u7AEF\u53E3
        port: 8719
          datasource:
            ds1:
              nacos:
                server-addr: 192.168.1.116:8848
                dataId: cloudalibaba-sentinel-service
                groupId: DEFAULT_GROUP
                data-type: json
                rule-type: flow
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
feign:
  sentinel:
    enabled: true #\u6FC0\u6D3Bsentinel \u5BF9feign\u7684\u652F\u6301